### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kidynamit** [powerman/vim-plugin-AnsiEsc#13]
The readme.md references version 8 its builds. Instructions should be updated for v13 (current version).

**Comment by powerman** [comment]
I don't really understand what you mean, but if you wanna somehow update README - make a PR.

**Comment by kidynamit** [comment]
I would like to create a PR but I can't. I am struggling to install the plugin.

I am using vim 8.0. The Vince Negri's patch only works with vim 7.0.

I created this issue so that the instructions for installing the plugin for vim 8.0 can be added to the readme.md.

**Comment by powerman** [comment]
Ah, I see. You don't need any patches for Vim 8, just install this plugin as you usually do. Readme "update" in this case actually means removing whole readme at all. :smile:

**Comment by kidynamit** [comment]
What should I have called it?

**Comment by powerman** [comment]
I don't understand, what do you mean?

**Comment by kidynamit** [comment]
What should I have named the issue? Instead of Update README.

**Comment by powerman** [comment]
You don't need to do anything, I've already removed outdated info from README.
