### ISSUE TITLE
lost syntax highlighting when no esc sequences in file

### ISSUE THREAD

**Issue by mckellyln** [powerman/vim-plugin-AnsiEsc#16]
Hi,

Thank you for this plugin.  Some files (such as my .bashrc) loose all syntax highlighting when I enable :AnsiEsc.
Does anyone know why or what to adjust to keep syntax highlighting with also handling esc codes if present ?

thx,
-m

**Comment by mckellyln** [comment]
It sort of seems if the file I am working on has '#' or some other chars - but not an esc color sequence then I loose all syntax highlighting.

**Comment by powerman** [comment]
I don't think it's possible to combine both ANSI and usual syntax highlight.

**Comment by mckellyln** [comment]
ok, thanks again.
