### ISSUE TITLE
How to use this plugin in Windows.

### ISSUE THREAD

**Issue by TayTTo** [powerman/vim-plugin-AnsiEsc#24]
I need a guide to use this plugin, it seems not work in Windows.
### Problem
![image](https://github.com/user-attachments/assets/e0e75a28-0a7d-43a9-8507-e5eeceb7f2bf)
When I use the tool named eza to raplace ls in gvim Terminal, it doesn't show the true color but the ANSII code instead.
When I use in powershell, it's normal.
I have install the plugin but it not work, here is the folder I store it
![image](https://github.com/user-attachments/assets/e4d7cf06-e374-4ce4-99ea-f36a0ef2d9b7)
After I install it, nothing change, the output of eza keep showing the ANSII code instead of the color.

**Comment by powerman** [comment]
I don't think this plugin is OS-specific, so at a glance it should work on Windows. Please provide more details, as in usual bugreport: what did you did, what happened, what you expected to happens.

**Comment by TayTTo** [comment]
@powerman I have edited my issue.

**Comment by powerman** [comment]
Installing the plugin is not enough, you need to execute `:AnsiEsc` vim command after loading text with ansi-sequences into vim. This command will toggle (you can execute it multiple times) how text is shown - raw (you see ansi sequences as is) or with colors (you won't see valid ansi sequences).

**Comment by powerman** [comment]
BTW, this plugin was developed many many years ago, when Vim does not had terminal feature, so it just wasn't designed for use cases like "make vim terminal automatically support ansi sequences".

**Comment by TayTTo** [comment]
When I run the command, this happens 
![image](https://github.com/user-attachments/assets/02e4d92e-529b-4033-a4a2-19802e2cf705)

**Comment by powerman** [comment]
BTW, In my vim-9.1.0366 (linux) terminal does support ansi sequences out of box without using AnsiEsc plugin:
![изображение](https://github.com/user-attachments/assets/eccb1ffe-399d-4c67-a832-caa41b0fdc85)
Terminal in Neovim-0.10.1 also show colors without any plugins.
So, maybe it's windows-related issue, but it's vim issue, not this plugin's.

**Comment by powerman** [comment]
BTW, "not an editor command" means you didn't installed the plugin. Just saving it into .vim/bundle/ is not enough - check docs of your vim plugin manager.

**Comment by TayTTo** [comment]
I'm using Vim plug as the plugin manager and I didn't see any doc about use it to install this plugin

**Comment by powerman** [comment]
Installation of this plugin is same as for any other, just check plug's documentation (probably you saved plugin into wrong directory or made some other trivial mistake - I didn't use plug and don't know how it works).

**Comment by TayTTo** [comment]
okay, I have install it and it didn't solve the problem, maybe it belong to vim and windows.
