### ISSUE TITLE
AnsiEsc overwrites my ctermbg=None

### ISSUE THREAD

**Issue by lucidstack** [powerman/vim-plugin-AnsiEsc#6]
Hi there,

Thanks for maintaining this essential plugin for us AnsiEsc'ers :grin: 

Unfortunately I have an issue with my background. In three pictures: 
<img width="1048" alt="screen shot 2016-04-07 at 10 41 27" src="https://cloud.githubusercontent.com/assets/1248581/14347207/c494ee4e-fcad-11e5-852d-695de9cdce6b.png">
<img width="1095" alt="screen shot 2016-04-07 at 10 42 07" src="https://cloud.githubusercontent.com/assets/1248581/14347214/c9bbab9c-fcad-11e5-9251-617c4b9d3051.png">
<img width="945" alt="screen shot 2016-04-07 at 10 42 16" src="https://cloud.githubusercontent.com/assets/1248581/14347216/cd8117da-fcad-11e5-9b2e-6c197f32e927.png">

I have 

```
highlight Normal  ctermbg=none
highlight NonText ctermbg=none
```

in my `.vimrc`, and I suppose that [this line](https://github.com/powerman/vim-plugin-AnsiEsc/blob/master/autoload/AnsiEsc.vim#L1539) is overriding my `ctermbg` for good, leaving me with the only solution of sourcing my `.vimrc` whenever I use AnsiEsc.

Am I doing something wrong? Would there be a way to tell AnsiEsc to apply the syntax rules only to the designated buffer, and leave the `ctermbg` untouched in the rest of the editor?

Thank you a lot in advance!

**Comment by powerman** [comment]
On my system this doesn't happens, so I suppose issue may be not in AnsiEsc but in your vimrc.
I didn't have `highlight` in .vimrc, instead I've moved my setup into `.vim/colors/myscheme.vim` and added `colorscheme myscheme` in .vimrc. Maybe this somehow helps work around this issue.

**Comment by lucidstack** [comment]
you are absolutely right, good sir. Tweaking my colour scheme a bit fixed the issue. AnsiEsc is just reapplying the syntax of my colour scheme, and rightfully skipping the `ctermbg` stuff in my `.vimrc`.

Thank you for enlightening me! :grinning:
